language: java

jdk:
  - openjdk17

sudo: false

env:
  global:
    - CODECOV_TOKEN=d444fc5a-f464-4ab2-94ca-a46f3eee15f2

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - asultangareev@gmail.com
    on_success: never # default: change
    on_failure: always # default: always